[sections.information_processing]
section_1 = "はじめに"
section_2 = "内容のアップデートについて"
section_3 = "おすすめのYouTubeチャンネル"
section_4 = "初心者向けパソコン講座"
section_5 = "パソコン基礎知識"
section_6 = "開発環境構築の哲学"
section_7 = "開発環境構築実践編"
section_8 = "コマンド基礎"
section_9 = "プログラミング言語概論"
section_10 = "AIを使ったプログラミングの手法"
section_11 = "実際にプログラミングをするときの設計"
section_12 = "Python基礎(+理論)"
section_13 = "今後書いていく内容"
section_14 = "その他の色々な話"
