[sections.information_processing]
section_1 = "はじめに ― このファイルに関しての説明"
section_2 = "内容のアップデートについて ― あなたも編集して作り上げていこう"
section_3 = "おすすめのYouTubeチャンネル ― ゆるコンピューター科学ラジオ"
section_4 = "初心者向けパソコン講座"
section_5 = "パソコン基礎知識"
section_6 = "AI時代の基礎的な知識"
section_7 = "開発環境構築の哲学 ― 知識がない人ほど模倣をしよう"
section_8 = "開発環境構築実践編"
section_9 = "コマンド基礎"
section_10 = "プログラミング言語概論"
section_11 = "AIを使ったプログラミングの手法"
section_12 = "実際にプログラミングをするときの設計"
section_13 = "Python基礎(+理論)"
section_14 = "今後書いていく内容"
section_15 = "その他の色々な話"
